name: List User Workbenches

on:
  workflow_dispatch: 

jobs:
  list-configurations:
    name: Get Workbench Configurations
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write     
      contents: read
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4


      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider:  ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.SERVICE_ACCOUNT }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Fetch Workbench Configurations and Add to Summary
        run: |
          echo "###  GCP Workbench Configurations for ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
          echo "| Property | Value |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- |" >> $GITHUB_STEP_SUMMARY
          
          # Capture output to a temporary file for processing
          gcloud workbench instances list --location="-" --format="json" > workbench_data.json

          # Extract data using jq and append to the GitHub Step Summary
          jq -r --arg ACTOR "${{ github.actor }}" '
            .[] | 
            select(.labels.github_username == $ACTOR) | 
            "| **Workbench Name** | \(.name | split("/")[-1]) |",
            "| Connection URL | [Click Here](\(.proxyUri // "#")) |",
            "| Owner Email | \(.creator // "N/A") |",
            "| Boot / Data Disk | \(.gceSetup.bootDisk.diskSizeGb)GB / \(.gceSetup.dataDisks[0].diskSizeGb)GB |",
            "| CPU Machine Type | \(.gceSetup.machineType | split("/")[-1]) |",
            "| GPU Attached | \(if (.gceSetup.acceleratorConfigs | length > 0) then "✅ \(.gceSetup.acceleratorConfigs[0].type)" else "❌ No" end) |",
            "| **Auto-Shutdown** | **\(.gceSetup.metadata."idle-timeout-minutes" // .gceSetup.metadata."idle-timeout" // .gceSetup.metadata.idleTimeout // "Not Detected") minutes** |",
            "| --- | --- |"
          ' workbench_data.json >> $GITHUB_STEP_SUMMARY

          # Also print to logs for verification
          cat $GITHUB_STEP_SUMMARY
